/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package expriments;

import java.io.FileOutputStream;
import java.io.IOException;

public class Library {
    public boolean someLibraryMethod() {
    	
    
    	
        return true;
    }
    
    public static void main(String[] args) {
		
    	
    	 // 파일에 쓸 데이터를 byte 배열로 생성
        byte[] data = {72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100};

        // 파일 경로 설정
        String filePath = "example.txt";

        // FileOutputStream을 사용하여 파일에 데이터를 씀
        try (FileOutputStream fos = new FileOutputStream(filePath)) {
            fos.write(data); // byte 배열을 파일에 씀
            System.out.println("파일에 데이터를 성공적으로 썼습니다.");
        } catch (IOException e) {
            System.err.println("파일에 데이터를 쓰는 도중 오류가 발생했습니다: " + e.getMessage());
        }
    	
    	
	}
}
